# Generated by Django 4.2.23 on 2025-07-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowrecord",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="borrowrecord",
            name="is_returned",
            field=models.BooleanField(default=False),
        ),
    ]
