# Generated by Django 4.2.23 on 2025-07-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_borrowrecord_due_date_borrowrecord_is_returned"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
