# Generated by Django 4.2.23 on 2025-07-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_visitor_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
