# Generated by Django 4.2.23 on 2025-07-09 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_visitor_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
