# Generated by Django 4.2.23 on 2025-07-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_visitor_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="rack_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="shelf_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
