# Generated by Django 4.2.23 on 2025-07-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_book_rack_number_book_shelf_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booklocation",
            name="block",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="booklocation",
            name="column",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="booklocation",
            name="position",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="booklocation",
            name="row",
            field=models.CharField(max_length=10),
        ),
    ]
