# Generated by Django 4.2.23 on 2025-07-11 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_alter_booklocation_block_alter_booklocation_column_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowrecord",
            name="visitor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrow_records",
                to="books.visitor",
            ),
        ),
    ]
