# Generated by Django 4.2.23 on 2025-07-11 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_alter_borrowrecord_visitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookreview",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="bookreview",
            name="is_spam",
            field=models.BooleanField(default=False),
        ),
    ]
