# Generated by Django 4.2.23 on 2025-07-14 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_bookreview_created_at_bookreview_is_spam"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("face_encoding", models.JSONField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Authorized", "Authorized"),
                            ("Unauthorized", "Unauthorized"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="visitor",
            name="face_encoding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
